package com.dhandata;

import android.os.Bundle;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;

public class WatchlistActivity extends AppCompatActivity {
    ArrayList<StockModel>stockModelArrayList =new ArrayList<>();

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        RecyclerView recyclerView=findViewById(R.id.itemCard);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        StockModel model=new StockModel("NSE","Reliance","2925","10");
        stockModelArrayList.add(new StockModel("NSE","TataMotor","977.55","-1.54"));
        stockModelArrayList.add(new StockModel("NSE", "Reliance Industries", "2440.50", "-0.75"));
        stockModelArrayList.add(new StockModel("BSE", "Reliance Industries", "2441.00", "-0.80"));
        stockModelArrayList.add(new StockModel("NSE", "TCS", "3475.25", "+12.50"));
        stockModelArrayList.add(new StockModel("BSE", "TCS", "3476.00", "+12.60"));
        stockModelArrayList.add(new StockModel("NSE", "HDFC Bank", "1532.20", "+6.30"));
        stockModelArrayList.add(new StockModel("BSE", "HDFC Bank", "1532.50", "+6.40"));
        stockModelArrayList.add(new StockModel("NSE", "Infosys", "1328.50", "-4.40"));
        stockModelArrayList.add(new StockModel("BSE", "Infosys", "1329.00", "-4.50"));
        stockModelArrayList.add(new StockModel("NSE", "ICICI Bank", "906.80", "+3.10"));
        stockModelArrayList.add(new StockModel("BSE", "ICICI Bank", "907.00", "+3.20"));
        stockModelArrayList.add(new StockModel("NSE", "HUL", "2441.55", "-2.50"));
        stockModelArrayList.add(new StockModel("BSE", "HUL", "2441.80", "-2.60"));
        stockModelArrayList.add(new StockModel("NSE", "Kotak Mahindra Bank", "1954.80", "+4.10"));
        stockModelArrayList.add(new StockModel("BSE", "Kotak Mahindra Bank", "1955.00", "+4.20"));
        stockModelArrayList.add(new StockModel("NSE", "L&T", "2648.75", "-5.60"));
        stockModelArrayList.add(new StockModel("BSE", "L&T", "2649.00", "-5.70"));
        stockModelArrayList.add(new StockModel("NSE", "SBI", "435.20", "+1.20"));
        stockModelArrayList.add(new StockModel("BSE", "SBI", "435.50", "+1.25"));
        stockModelArrayList.add(new StockModel("NSE", "Bajaj Finance", "5950.00", "+18.90"));
        stockModelArrayList.add(new StockModel("BSE", "Bajaj Finance", "5951.00", "+19.00"));
        stockModelArrayList.add(new StockModel("NSE", "Asian Paints", "3200.50", "-3.70"));
        stockModelArrayList.add(new StockModel("BSE", "Asian Paints", "3201.00", "-3.80"));
        stockModelArrayList.add(new StockModel("NSE", "Axis Bank", "736.20", "+2.50"));
        stockModelArrayList.add(new StockModel("BSE", "Axis Bank", "736.40", "+2.60"));
        stockModelArrayList.add(new StockModel("NSE", "Maruti Suzuki", "8390.00", "-21.50"));
        stockModelArrayList.add(new StockModel("BSE", "Maruti Suzuki", "8391.00", "-21.60"));
        stockModelArrayList.add(new StockModel("NSE", "SBI Life Insurance", "1264.75", "+4.00"));
        stockModelArrayList.add(new StockModel("BSE", "SBI Life Insurance", "1265.00", "+4.10"));
        stockModelArrayList.add(new StockModel("NSE", "Adani Enterprises", "1712.45", "-8.20"));
        stockModelArrayList.add(new StockModel("BSE", "Adani Enterprises", "1712.60", "-8.30"));
        stockModelArrayList.add(new StockModel("NSE", "Bharti Airtel", "713.20", "+3.20"));
        stockModelArrayList.add(new StockModel("BSE", "Bharti Airtel", "713.50", "+3.30"));
        stockModelArrayList.add(new StockModel("NSE", "HDFC Life Insurance", "709.00", "-2.50"));
        stockModelArrayList.add(new StockModel("BSE", "HDFC Life Insurance", "709.30", "-2.60"));
        stockModelArrayList.add(new StockModel("NSE", "Wipro", "407.75", "+0.95"));
        stockModelArrayList.add(new StockModel("BSE", "Wipro", "407.90", "+1.00"));
        stockModelArrayList.add(new StockModel("NSE", "Tata Steel", "1030.55", "-5.70"));
        stockModelArrayList.add(new StockModel("BSE", "Tata Steel", "1030.80", "-5.80"));
        stockModelArrayList.add(new StockModel("NSE", "NTPC", "125.80", "+0.45"));
        stockModelArrayList.add(new StockModel("BSE", "NTPC", "125.90", "+0.50"));
        stockModelArrayList.add(new StockModel("NSE", "IndusInd Bank", "977.20", "+5.10"));
        stockModelArrayList.add(new StockModel("BSE", "IndusInd Bank", "977.40", "+5.20"));
        stockModelArrayList.add(new StockModel("NSE", "Tech Mahindra", "1078.00", "-3.90"));
        stockModelArrayList.add(new StockModel("BSE", "Tech Mahindra", "1078.20", "-4.00"));
        stockModelArrayList.add(new StockModel("NSE", "Adani Green Energy", "1187.30", "+7.60"));
        stockModelArrayList.add(new StockModel("BSE", "Adani Green Energy", "1187.50", "+7.70"));
        stockModelArrayList.add(new StockModel("NSE", "Hindalco Industries", "416.20", "-3.10"));
        stockModelArrayList.add(new StockModel("BSE", "Hindalco Industries", "416.50", "-3.20"));
        stockModelArrayList.add(new StockModel("NSE", "Titan Company", "1524.75", "+9.00"));
        stockModelArrayList.add(new StockModel("BSE", "Titan Company", "1525.00", "+9.10"));
        stockModelArrayList.add(new StockModel("NSE", "Mahindra & Mahindra", "820.25", "+4.60"));
        stockModelArrayList.add(new StockModel("BSE", "Mahindra & Mahindra", "820.50", "+4.70"));
        stockModelArrayList.add(new StockModel("NSE", "Bharat Petroleum", "441.80", "-1.20"));
        stockModelArrayList.add(new StockModel("BSE", "Bharat Petroleum", "442.00", "-1.25"));
        stockModelArrayList.add(new StockModel("NSE", "Sun Pharmaceuticals", "777.90", "+0.75"));
        stockModelArrayList.add(new StockModel("BSE", "Sun Pharmaceuticals", "778.00", "+0.80"));
        stockModelArrayList.add(new StockModel("NSE", "Bajaj Finserv", "1300.20", "+7.30"));
        stockModelArrayList.add(new StockModel("BSE", "Bajaj Finserv", "1300.50", "+7.40"));
        stockModelArrayList.add(new StockModel("NSE", "HCL Technologies", "1055.40", "-6.80"));
        stockModelArrayList.add(new StockModel("BSE", "HCL Technologies", "1055.70", "-6.90"));
        stockModelArrayList.add(new StockModel("NSE", "Power Grid", "214.70", "+0.35"));
        stockModelArrayList.add(new StockModel("BSE", "Power Grid", "214.80", "+0.40"));
        stockModelArrayList.add(new StockModel("NSE", "Eicher Motors", "3265.10", "-17.80"));
        stockModelArrayList.add(new StockModel("BSE", "Eicher Motors", "3265.50", "-17.90"));
        stockModelArrayList.add(new StockModel("NSE", "Grasim Industries", "1788.30", "+4.60"));
        stockModelArrayList.add(new StockModel("BSE", "Grasim Industries", "1788.60", "+4.70"));
        stockModelArrayList.add(new StockModel("NSE", "State Bank of India", "440.50", "-0.80"));
        stockModelArrayList.add(new StockModel("BSE", "State Bank of India", "440.75", "-0.85"));
        stockModelArrayList.add(new StockModel("NSE", "Bajaj Auto", "3680.30", "+14.10"));
        stockModelArrayList.add(new StockModel("BSE", "Bajaj Auto", "3681.00", "+14.20"));
        stockModelArrayList.add(new StockModel("NSE", "Tata Consumer Products", "723.60", "-3.10"));
        stockModelArrayList.add(new StockModel("BSE", "Tata Consumer Products", "724.00", "-3.15"));
        stockModelArrayList.add(new StockModel("NSE", "Mphasis", "1798.20", "+5.00"));
        stockModelArrayList.add(new StockModel("BSE", "Mphasis", "1798.50", "+5.10"));
        stockModelArrayList.add(new StockModel("NSE", "Godrej Properties", "1257.70", "+9.90"));
        stockModelArrayList.add(new StockModel("BSE", "Godrej Properties", "1258.00", "+10.00"));
        stockModelArrayList.add(new StockModel("NSE", "Dr. Reddy's Laboratories", "4852.30", "-8.40"));
        stockModelArrayList.add(new StockModel("BSE", "Dr. Reddy's Laboratories", "4852.50", "-8.50"));
        stockModelArrayList.add(new StockModel("NSE", "Adani Ports & SEZ", "727.50", "+4.00"));
        stockModelArrayList.add(new StockModel("BSE", "Adani Ports & SEZ", "728.00", "+4.10"));
        stockModelArrayList.add(new StockModel("NSE", "JSW Steel", "759.90", "+3.50"));
        stockModelArrayList.add(new StockModel("BSE", "JSW Steel", "760.00", "+3.60"));
        stockModelArrayList.add(new StockModel("NSE", "Hindustan Unilever", "2395.25", "+0.95"));
        stockModelArrayList.add(new StockModel("BSE", "Hindustan Unilever", "2395.50", "+1.00"));
        stockModelArrayList.add(new StockModel("NSE", "Bank of Baroda", "80.10", "-0.55"));
        stockModelArrayList.add(new StockModel("BSE", "Bank of Baroda", "80.20", "-0.60"));
        stockModelArrayList.add(new StockModel("NSE", "L&T Finance Holdings", "101.50", "+1.15"));
        stockModelArrayList.add(new StockModel("BSE", "L&T Finance Holdings", "101.70", "+1.20"));
        stockModelArrayList.add(new StockModel("NSE", "Lupin", "970.10", "-3.20"));
        stockModelArrayList.add(new StockModel("BSE", "Lupin", "970.50", "-3.30"));
        stockModelArrayList.add(new StockModel("NSE", "United Spirits", "595.60", "+1.75"));
        stockModelArrayList.add(new StockModel("BSE", "United Spirits", "595.80", "+1.80"));
        stockModelArrayList.add(new StockModel("NSE", "Ashok Leyland", "130.70", "+0.80"));
        stockModelArrayList.add(new StockModel("BSE", "Ashok Leyland", "130.90", "+0.85"));
        stockModelArrayList.add(new StockModel("NSE", "Nestlé India", "17840.00", "-50.30"));
        stockModelArrayList.add(new StockModel("BSE", "Nestlé India", "17841.00", "-50.40"));
        stockModelArrayList.add(new StockModel("NSE", "Cipla", "951.20", "+2.10"));
        stockModelArrayList.add(new StockModel("BSE", "Cipla", "951.40", "+2.20"));
        stockModelArrayList.add(new StockModel("NSE", "Piramal Enterprises", "1527.80", "-12.10"));
        stockModelArrayList.add(new StockModel("BSE", "Piramal Enterprises", "1528.00", "-12.20"));
        stockModelArrayList.add(new StockModel("NSE", "Motherson Sumi Systems", "249.75", "+1.90"));
        stockModelArrayList.add(new StockModel("BSE", "Motherson Sumi Systems", "250.00", "+1.95"));
        stockModelArrayList.add(new StockModel("NSE", "Zee Entertainment", "248.00", "-4.10"));
        stockModelArrayList.add(new StockModel("BSE", "Zee Entertainment", "248.50", "-4.20"));
        stockModelArrayList.add(new StockModel("NSE", "Coal India", "125.10", "+0.65"));
        stockModelArrayList.add(new StockModel("BSE", "Coal India", "125.30", "+0.70"));
        stockModelArrayList.add(new StockModel("NSE", "Apollo Hospitals", "5075.00", "+15.20"));
        stockModelArrayList.add(new StockModel("BSE", "Apollo Hospitals", "5075.50", "+15.30"));
        stockModelArrayList.add(new StockModel("NSE", "Hindustan Zinc", "305.80", "-1.60"));
        stockModelArrayList.add(new StockModel("BSE", "Hindustan Zinc", "306.00", "-1.70"));
        stockModelArrayList.add(new StockModel("NSE", "Voltas", "1012.40", "+3.50"));
        stockModelArrayList.add(new StockModel("BSE", "Voltas", "1012.80", "+3.60"));
        stockModelArrayList.add(new StockModel("NSE", "Pidilite Industries", "2034.10", "-7.90"));
        stockModelArrayList.add(new StockModel("BSE", "Pidilite Industries", "2034.50", "-8.00"));
        stockModelArrayList.add(new StockModel("NSE", "ACC", "1815.40", "+8.10"));
        stockModelArrayList.add(new StockModel("BSE", "ACC", "1815.80", "+8.20"));
        stockModelArrayList.add(new StockModel("NSE", "Muthoot Finance", "1170.50", "-6.20"));
        stockModelArrayList.add(new StockModel("BSE", "Muthoot Finance", "1170.80", "-6.30"));
        stockModelArrayList.add(new StockModel("NSE", "Bata India", "1710.50", "+5.40"));
        stockModelArrayList.add(new StockModel("BSE", "Bata India", "1710.90", "+5.50"));
        stockModelArrayList.add(new StockModel("NSE", "SBI Cards & Payments", "1018.80", "+4.20"));
        stockModelArrayList.add(new StockModel("BSE", "SBI Cards & Payments", "1019.00", "+4.25"));
        stockModelArrayList.add(new StockModel("NSE", "Jubilant FoodWorks", "3188.00", "-15.80"));
        stockModelArrayList.add(new StockModel("BSE", "Jubilant FoodWorks", "3188.50", "-15.90"));

        RecyclerStockAdapter adapter = new RecyclerStockAdapter(this,stockModelArrayList);
        recyclerView.setAdapter(adapter);
    }
}
